Fix deserialization error
System.Text.Json.JsonException: The JSON value could not be converted to DigitalFoundation.Core.Services.Quote.Enums.ProductType